### ISSUE TITLE
NPE at android.view.GhostView.calculateMatrix(GhostView.java:89)

### ISSUE THREAD

**Issue by ChaosLeung** [ChaosLeong/FxcnBeta#15]
RecyclerView item 与 ContentActivity 之间频繁地多次切换时会触发该异常，主要由 Shared Element Transition 引起

```
Process: org.chaos.fx.cnbeta, PID: 14122
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.transformMatrixToGlobal(android.graphics.Matrix)' on a null object reference
    at android.view.GhostView.calculateMatrix(GhostView.java:89)
    at android.app.ActivityTransitionCoordinator$GhostViewListeners.onPreDraw(ActivityTransitionCoordinator.java:1000)
    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2235)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1272)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6396)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
    at android.view.Choreographer.doCallbacks(Choreographer.java:683)
    at android.view.Choreographer.doFrame(Choreographer.java:619)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6209)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by ChaosLeung** [comment]
[GhostView.java](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/GhostView.java) 的 `calculateMatrix` 会先调用 `view.getParent()` 再执行 transformMatrixToGlobal。

```
public static void calculateMatrix(View view, ViewGroup host, Matrix matrix) {
    ViewGroup parent = (ViewGroup) view.getParent(); // 87
    matrix.reset(); // 88
    parent.transformMatrixToGlobal(matrix);// 89行
    matrix.preTranslate(-parent.getScrollX(), -parent.getScrollY());
    host.transformMatrixToLocal(matrix);
}
```

由于 RecyclerView 在 `onDetachedFromWindow` 时会从布局中移除所有的 itemView，所以从 ContentActivity 返回原界面时，偶尔对应的 itemView 还未被添加到布局中（onChildViewAttachedToWindow），于是造成了 NPE。

**Comment by ChaosLeung** [comment]
在 Debug 过程中发现，点击的 itemView 与对应 position 的 ViewHolder.itemView 不是同一个 view。但在正常情况下（非点开页面后马上关），两个 view 是一致的。未知会导致两个 itemView 不一致的原因。

StackOverFlow 上有人提到这一点：http://stackoverflow.com/a/28744179/3351990
修复该问题只需确保点击的 itemView 与 Shared Element 的 itemView 是一致的。
